FROM nass

USER root
RUN apk add -U npm go neovim file entr bash-completion pass-bash-completion
RUN npm i -g pnpm vite

WORKDIR /nass
USER nass
RUN ./scripts/init_pass.sh

ENTRYPOINT ./nass -c "${CONF}" -u "${USERS}"

