FROM nass

USER root
RUN apk add -U npm go neovim file bash-completion pass-bash-completion
RUN npm i -g yarn vite

WORKDIR /nass
USER nass
RUN ./scripts/init_pass.sh

ENTRYPOINT ./nass -c "${CONF}" -u "${USERS}"

