FROM nass

USER root

RUN apk add -U npm go neovim file entr
RUN npm i -g pnpm vite

WORKDIR /root
COPY . .
RUN go get -u
RUN pnpm i
RUN ./scripts/dev_setup.sh

ENTRYPOINT ["./nass", "-c", "${CONF}", "-u", "${USERS}"]

